### ISSUE TITLE
NameError: name 'core' is not defined

### ISSUE THREAD

**Issue by mileo** [damies13/rfswarm#113]
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Robot Framework Swarm: Manager 
	Version 1.0.0 
	Configuration File:  /home/pos/.rfswarm/RFSwarmManager.ini 
Unable to create resultsdir: /usr/local/lib/python3.8/dist-packages/rfswarm_manager/results 
 [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/rfswarm_manager/results' 
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rfswarm_manager/rfswarm.py", line 788, in ensure_db
    os.mkdir(self.resultsdir)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/rfswarm_manager/results'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rfswarm_manager/rfswarm.py", line 646, in run_db_thread
    self.ensure_db()
  File "/usr/local/lib/python3.8/dist-packages/rfswarm_manager/rfswarm.py", line 792, in ensure_db
    core.on_closing()
NameError: name 'core' is not defined
```

**Comment by mileo** [comment]
Solved, just install without sudo.

```pip install rfswarm-manager```
