### ISSUE TITLE
Improve error handling when agent can't read the _output.xml file

### ISSUE THREAD

**Issue by damies13** [damies13/rfswarm#19]
```
RFSwarmAgent: mainloop: Running 2019-11-25 10:33:27 ( 1574658207 )isrunning: True isconnected: True
[ ERROR ] Parsing 'World'' failed: File or directory to execute does not exist.

Try --help for usage information.
Exception in thread Thread-85:
Traceback (most recent call last):
File "C:\Users\ROHITKUM\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
self.run()
File "C:\Users\ROHITKUM\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "C:/Users/ROHITKUM/PycharmProjects/Python_rf1/rfswarm_agent.py", line 479, in run_process_output
tree = ET.parse(outputFile)
File "C:\Users\ROHITKUM\AppData\Local\Programs\Python\Python37-32\lib\xml\etree\ElementTree.py", line 1197, in parse
tree.parse(source, parser)
File "C:\Users\ROHITKUM\AppData\Local\Programs\Python\Python37-32\lib\xml\etree\ElementTree.py", line 587, in parse
source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\ROHITKUM\AppData\Local\Temp\rfswarmagent\logs\Scenario_1574658179\TC001_OpenCloseBrowser_1_5_1574658208\Hello_World_output.xml'

RFSwarmAgent: mainloop: Running 2019-11-25 10:33:29 ( 1574658209 )isrunning: True isconnected: True
```

**Comment by damies13** [comment]
rfswarm_agent.py
Line 461: 		t = threading.Thread(target=self.run_process_output, args=(outputFile, self.jobs[jobid]["ScriptIndex"], self.jobs[jobid]["VUser"], self.jobs[jobid]["Iteration"]))

add an if clause here to check if the file exists, can also check if the stdout / stderr files exist and print them as places to check why.
