### ISSUE TITLE
Since v0.5.0 launching the GUI fails if there is no existing ini file 

### ISSUE THREAD

**Issue by damies13** [damies13/rfswarm#49]
**Describe the bug**
Since v0.5.0 launching the GUI fails if there is no existing ini file 

**To Reproduce**
1. delete the ini file
2. launch GUI

**Expected behavior**
Application launches and creates new ini file 

**Additional context**

Robot Framework Swarm: GUI/Server
	Version v0.5.0-beta
Traceback (most recent call last):
  File "rfswarm.py", line 3885, in <module>
    core = RFSwarmCore()
  File "rfswarm.py", line 1090, in __init__
    base.gui = RFSwarmGUI()
  File "rfswarm.py", line 1856, in __init__
    self.BuildUI()
  File "rfswarm.py", line 1993, in BuildUI
    self.BuildRun(r)
  File "rfswarm.py", line 3273, in BuildRun
    self.display_run['display_index'].set(base.str2bool(base.config['Run']['display_index']))
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'Run'

**Comment by damies13** [comment]
resolved in v0.5.1-beta
