### ISSUE TITLE
--nogui stack dump creating the results directory

### ISSUE THREAD

**Issue by damies13** [damies13/rfswarm#80]
**Describe the bug**
When starting a test with --nogui multiple threads try to create the results directory and then one will stack dump, this needs to be handled

**To Reproduce**

run test scenario with --nogui

**Expected behavior**
Thread safe handling of creating the result directory

**Screenshots**
```
C:\Users\Dave>rfswarm --nogui -s Y:\robot-and-scenario\xpto2.rfs -a 3
Robot Framework Swarm: Manager
        Version 0.6.4
        Configuration File:  c:\users\dave\appdata\local\programs\python\python37\lib\site-packages\rfswarm_manager\RFSwarmManager.ini
Robot Framework Swarm: Manager
        Version 0.6.4
        Configuration File:  c:\users\dave\appdata\local\programs\python\python37\lib\site-packages\rfswarm_manager\RFSwarmManager.ini
<rfswarm.RFSwarmCore object at 0x000001968ECB2108>
Test Started:    1616809048 [ 2021-03-27 11:37:28 ]
Exception in thread Thread-7:
Traceback (most recent call last):
  File "c:\users\dave\appdata\local\programs\python\python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "c:\users\dave\appdata\local\programs\python\python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\dave\appdata\local\programs\python\python37\lib\site-packages\rfswarm_manager\rfswarm.py", line 563, in run_db_thread
    self.ensure_db()
  File "c:\users\dave\appdata\local\programs\python\python37\lib\site-packages\rfswarm_manager\rfswarm.py", line 705, in ensure_db
    os.mkdir(base.datapath)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'c:\\users\\dave\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\rfswarm_manager\\results\\20210327_113728_xpto2'

Test Completed:  1616809162 [ 2021-03-27 11:40:27 ]
Shutdown Agent Manager

```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - rfswarm Version 0.6.4

**Additional context**
--nogui

**Comment by damies13** [comment]
Fixed
