### ISSUE TITLE
ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by damies13** [damies13/rfswarm#95]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1884, in __call__
    return self.func(*args)
  File "/Users/dave/Documents/GitHub/rfswarm/rfswarm_manager/./rfswarm.py", line 4996, in <lambda>
    schedWindow.time.trace('w', lambda *args: self.ss_validate(schedWindow, args))
  File "/Users/dave/Documents/GitHub/rfswarm/rfswarm_manager/./rfswarm.py", line 5108, in ss_validate
    stime = "{:02}:{:02}:{:02}".format(int(atime[0]),int(atime[1]),int(atime[2]))
ValueError: invalid literal for int() with base 10: ''

probably introduced by issue #89

**Comment by damies13** [comment]
I can reproduce this by overtyping the minutes when scheduling the start time

**Comment by damies13** [comment]
Issue merged into branch v0.9.0
